// Code generated by mockery v2.36.1. DO NOT EDIT.

package clory_test

import (
	client "github.com/ory/client-go"

	context "context"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockFrontendAPI is an autogenerated mock type for the FrontendAPI type
type MockFrontendAPI struct {
	mock.Mock
}

type MockFrontendAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFrontendAPI) EXPECT() *MockFrontendAPI_Expecter {
	return &MockFrontendAPI_Expecter{mock: &_m.Mock}
}

// ToSession provides a mock function with given fields: ctx
func (_m *MockFrontendAPI) ToSession(ctx context.Context) client.FrontendAPIToSessionRequest {
	ret := _m.Called(ctx)

	var r0 client.FrontendAPIToSessionRequest
	if rf, ok := ret.Get(0).(func(context.Context) client.FrontendAPIToSessionRequest); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(client.FrontendAPIToSessionRequest)
	}

	return r0
}

// MockFrontendAPI_ToSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToSession'
type MockFrontendAPI_ToSession_Call struct {
	*mock.Call
}

// ToSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFrontendAPI_Expecter) ToSession(ctx interface{}) *MockFrontendAPI_ToSession_Call {
	return &MockFrontendAPI_ToSession_Call{Call: _e.mock.On("ToSession", ctx)}
}

func (_c *MockFrontendAPI_ToSession_Call) Run(run func(ctx context.Context)) *MockFrontendAPI_ToSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFrontendAPI_ToSession_Call) Return(_a0 client.FrontendAPIToSessionRequest) *MockFrontendAPI_ToSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFrontendAPI_ToSession_Call) RunAndReturn(run func(context.Context) client.FrontendAPIToSessionRequest) *MockFrontendAPI_ToSession_Call {
	_c.Call.Return(run)
	return _c
}

// ToSessionExecute provides a mock function with given fields: r
func (_m *MockFrontendAPI) ToSessionExecute(r client.FrontendAPIToSessionRequest) (*client.Session, *http.Response, error) {
	ret := _m.Called(r)

	var r0 *client.Session
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(client.FrontendAPIToSessionRequest) (*client.Session, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(client.FrontendAPIToSessionRequest) *client.Session); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(client.FrontendAPIToSessionRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(client.FrontendAPIToSessionRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFrontendAPI_ToSessionExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToSessionExecute'
type MockFrontendAPI_ToSessionExecute_Call struct {
	*mock.Call
}

// ToSessionExecute is a helper method to define mock.On call
//   - r client.FrontendAPIToSessionRequest
func (_e *MockFrontendAPI_Expecter) ToSessionExecute(r interface{}) *MockFrontendAPI_ToSessionExecute_Call {
	return &MockFrontendAPI_ToSessionExecute_Call{Call: _e.mock.On("ToSessionExecute", r)}
}

func (_c *MockFrontendAPI_ToSessionExecute_Call) Run(run func(r client.FrontendAPIToSessionRequest)) *MockFrontendAPI_ToSessionExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.FrontendAPIToSessionRequest))
	})
	return _c
}

func (_c *MockFrontendAPI_ToSessionExecute_Call) Return(_a0 *client.Session, _a1 *http.Response, _a2 error) *MockFrontendAPI_ToSessionExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFrontendAPI_ToSessionExecute_Call) RunAndReturn(run func(client.FrontendAPIToSessionRequest) (*client.Session, *http.Response, error)) *MockFrontendAPI_ToSessionExecute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFrontendAPI creates a new instance of MockFrontendAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFrontendAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFrontendAPI {
	mock := &MockFrontendAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
