with-expecter: true
filename: "mock_{{.InterfaceNameLower}}.go"
dir: "{{.InterfaceDir}}/{{.PackageName}}mock"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}mock"
packages:
  github.com/crewlinker/clgo/clory:
    interfaces:
      FrontendAPI: 
  github.com/crewlinker/clgo/clconnect:
    interfaces:
      Ory:
  github.com/crewlinker/clgo/clworkos:
    interfaces:
      UserManagement:
      Organizations: