// Code generated by mockery v2.52.2. DO NOT EDIT.

package clworkosmock

import (
	context "context"
	url "net/url"

	mock "github.com/stretchr/testify/mock"

	usermanagement "github.com/workos/workos-go/v4/pkg/usermanagement"
)

// MockUserManagement is an autogenerated mock type for the UserManagement type
type MockUserManagement struct {
	mock.Mock
}

type MockUserManagement_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserManagement) EXPECT() *MockUserManagement_Expecter {
	return &MockUserManagement_Expecter{mock: &_m.Mock}
}

// AuthenticateWithCode provides a mock function with given fields: ctx, opts
func (_m *MockUserManagement) AuthenticateWithCode(ctx context.Context, opts usermanagement.AuthenticateWithCodeOpts) (usermanagement.AuthenticateResponse, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateWithCode")
	}

	var r0 usermanagement.AuthenticateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.AuthenticateWithCodeOpts) (usermanagement.AuthenticateResponse, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.AuthenticateWithCodeOpts) usermanagement.AuthenticateResponse); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(usermanagement.AuthenticateResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermanagement.AuthenticateWithCodeOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_AuthenticateWithCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateWithCode'
type MockUserManagement_AuthenticateWithCode_Call struct {
	*mock.Call
}

// AuthenticateWithCode is a helper method to define mock.On call
//   - ctx context.Context
//   - opts usermanagement.AuthenticateWithCodeOpts
func (_e *MockUserManagement_Expecter) AuthenticateWithCode(ctx interface{}, opts interface{}) *MockUserManagement_AuthenticateWithCode_Call {
	return &MockUserManagement_AuthenticateWithCode_Call{Call: _e.mock.On("AuthenticateWithCode", ctx, opts)}
}

func (_c *MockUserManagement_AuthenticateWithCode_Call) Run(run func(ctx context.Context, opts usermanagement.AuthenticateWithCodeOpts)) *MockUserManagement_AuthenticateWithCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermanagement.AuthenticateWithCodeOpts))
	})
	return _c
}

func (_c *MockUserManagement_AuthenticateWithCode_Call) Return(_a0 usermanagement.AuthenticateResponse, _a1 error) *MockUserManagement_AuthenticateWithCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_AuthenticateWithCode_Call) RunAndReturn(run func(context.Context, usermanagement.AuthenticateWithCodeOpts) (usermanagement.AuthenticateResponse, error)) *MockUserManagement_AuthenticateWithCode_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateWithPassword provides a mock function with given fields: ctx, opts
func (_m *MockUserManagement) AuthenticateWithPassword(ctx context.Context, opts usermanagement.AuthenticateWithPasswordOpts) (usermanagement.AuthenticateResponse, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateWithPassword")
	}

	var r0 usermanagement.AuthenticateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.AuthenticateWithPasswordOpts) (usermanagement.AuthenticateResponse, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.AuthenticateWithPasswordOpts) usermanagement.AuthenticateResponse); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(usermanagement.AuthenticateResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermanagement.AuthenticateWithPasswordOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_AuthenticateWithPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateWithPassword'
type MockUserManagement_AuthenticateWithPassword_Call struct {
	*mock.Call
}

// AuthenticateWithPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - opts usermanagement.AuthenticateWithPasswordOpts
func (_e *MockUserManagement_Expecter) AuthenticateWithPassword(ctx interface{}, opts interface{}) *MockUserManagement_AuthenticateWithPassword_Call {
	return &MockUserManagement_AuthenticateWithPassword_Call{Call: _e.mock.On("AuthenticateWithPassword", ctx, opts)}
}

func (_c *MockUserManagement_AuthenticateWithPassword_Call) Run(run func(ctx context.Context, opts usermanagement.AuthenticateWithPasswordOpts)) *MockUserManagement_AuthenticateWithPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermanagement.AuthenticateWithPasswordOpts))
	})
	return _c
}

func (_c *MockUserManagement_AuthenticateWithPassword_Call) Return(_a0 usermanagement.AuthenticateResponse, _a1 error) *MockUserManagement_AuthenticateWithPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_AuthenticateWithPassword_Call) RunAndReturn(run func(context.Context, usermanagement.AuthenticateWithPasswordOpts) (usermanagement.AuthenticateResponse, error)) *MockUserManagement_AuthenticateWithPassword_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateWithRefreshToken provides a mock function with given fields: ctx, opts
func (_m *MockUserManagement) AuthenticateWithRefreshToken(ctx context.Context, opts usermanagement.AuthenticateWithRefreshTokenOpts) (usermanagement.RefreshAuthenticationResponse, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateWithRefreshToken")
	}

	var r0 usermanagement.RefreshAuthenticationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.AuthenticateWithRefreshTokenOpts) (usermanagement.RefreshAuthenticationResponse, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.AuthenticateWithRefreshTokenOpts) usermanagement.RefreshAuthenticationResponse); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(usermanagement.RefreshAuthenticationResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermanagement.AuthenticateWithRefreshTokenOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_AuthenticateWithRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateWithRefreshToken'
type MockUserManagement_AuthenticateWithRefreshToken_Call struct {
	*mock.Call
}

// AuthenticateWithRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - opts usermanagement.AuthenticateWithRefreshTokenOpts
func (_e *MockUserManagement_Expecter) AuthenticateWithRefreshToken(ctx interface{}, opts interface{}) *MockUserManagement_AuthenticateWithRefreshToken_Call {
	return &MockUserManagement_AuthenticateWithRefreshToken_Call{Call: _e.mock.On("AuthenticateWithRefreshToken", ctx, opts)}
}

func (_c *MockUserManagement_AuthenticateWithRefreshToken_Call) Run(run func(ctx context.Context, opts usermanagement.AuthenticateWithRefreshTokenOpts)) *MockUserManagement_AuthenticateWithRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermanagement.AuthenticateWithRefreshTokenOpts))
	})
	return _c
}

func (_c *MockUserManagement_AuthenticateWithRefreshToken_Call) Return(_a0 usermanagement.RefreshAuthenticationResponse, _a1 error) *MockUserManagement_AuthenticateWithRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_AuthenticateWithRefreshToken_Call) RunAndReturn(run func(context.Context, usermanagement.AuthenticateWithRefreshTokenOpts) (usermanagement.RefreshAuthenticationResponse, error)) *MockUserManagement_AuthenticateWithRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganizationMembership provides a mock function with given fields: ctx, opts
func (_m *MockUserManagement) CreateOrganizationMembership(ctx context.Context, opts usermanagement.CreateOrganizationMembershipOpts) (usermanagement.OrganizationMembership, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationMembership")
	}

	var r0 usermanagement.OrganizationMembership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.CreateOrganizationMembershipOpts) (usermanagement.OrganizationMembership, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.CreateOrganizationMembershipOpts) usermanagement.OrganizationMembership); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(usermanagement.OrganizationMembership)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermanagement.CreateOrganizationMembershipOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_CreateOrganizationMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizationMembership'
type MockUserManagement_CreateOrganizationMembership_Call struct {
	*mock.Call
}

// CreateOrganizationMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - opts usermanagement.CreateOrganizationMembershipOpts
func (_e *MockUserManagement_Expecter) CreateOrganizationMembership(ctx interface{}, opts interface{}) *MockUserManagement_CreateOrganizationMembership_Call {
	return &MockUserManagement_CreateOrganizationMembership_Call{Call: _e.mock.On("CreateOrganizationMembership", ctx, opts)}
}

func (_c *MockUserManagement_CreateOrganizationMembership_Call) Run(run func(ctx context.Context, opts usermanagement.CreateOrganizationMembershipOpts)) *MockUserManagement_CreateOrganizationMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermanagement.CreateOrganizationMembershipOpts))
	})
	return _c
}

func (_c *MockUserManagement_CreateOrganizationMembership_Call) Return(_a0 usermanagement.OrganizationMembership, _a1 error) *MockUserManagement_CreateOrganizationMembership_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_CreateOrganizationMembership_Call) RunAndReturn(run func(context.Context, usermanagement.CreateOrganizationMembershipOpts) (usermanagement.OrganizationMembership, error)) *MockUserManagement_CreateOrganizationMembership_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorizationURL provides a mock function with given fields: opts
func (_m *MockUserManagement) GetAuthorizationURL(opts usermanagement.GetAuthorizationURLOpts) (*url.URL, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationURL")
	}

	var r0 *url.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(usermanagement.GetAuthorizationURLOpts) (*url.URL, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(usermanagement.GetAuthorizationURLOpts) *url.URL); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(usermanagement.GetAuthorizationURLOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_GetAuthorizationURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizationURL'
type MockUserManagement_GetAuthorizationURL_Call struct {
	*mock.Call
}

// GetAuthorizationURL is a helper method to define mock.On call
//   - opts usermanagement.GetAuthorizationURLOpts
func (_e *MockUserManagement_Expecter) GetAuthorizationURL(opts interface{}) *MockUserManagement_GetAuthorizationURL_Call {
	return &MockUserManagement_GetAuthorizationURL_Call{Call: _e.mock.On("GetAuthorizationURL", opts)}
}

func (_c *MockUserManagement_GetAuthorizationURL_Call) Run(run func(opts usermanagement.GetAuthorizationURLOpts)) *MockUserManagement_GetAuthorizationURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(usermanagement.GetAuthorizationURLOpts))
	})
	return _c
}

func (_c *MockUserManagement_GetAuthorizationURL_Call) Return(_a0 *url.URL, _a1 error) *MockUserManagement_GetAuthorizationURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_GetAuthorizationURL_Call) RunAndReturn(run func(usermanagement.GetAuthorizationURLOpts) (*url.URL, error)) *MockUserManagement_GetAuthorizationURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogoutURL provides a mock function with given fields: opts
func (_m *MockUserManagement) GetLogoutURL(opts usermanagement.GetLogoutURLOpts) (*url.URL, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for GetLogoutURL")
	}

	var r0 *url.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(usermanagement.GetLogoutURLOpts) (*url.URL, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(usermanagement.GetLogoutURLOpts) *url.URL); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(usermanagement.GetLogoutURLOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_GetLogoutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogoutURL'
type MockUserManagement_GetLogoutURL_Call struct {
	*mock.Call
}

// GetLogoutURL is a helper method to define mock.On call
//   - opts usermanagement.GetLogoutURLOpts
func (_e *MockUserManagement_Expecter) GetLogoutURL(opts interface{}) *MockUserManagement_GetLogoutURL_Call {
	return &MockUserManagement_GetLogoutURL_Call{Call: _e.mock.On("GetLogoutURL", opts)}
}

func (_c *MockUserManagement_GetLogoutURL_Call) Run(run func(opts usermanagement.GetLogoutURLOpts)) *MockUserManagement_GetLogoutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(usermanagement.GetLogoutURLOpts))
	})
	return _c
}

func (_c *MockUserManagement_GetLogoutURL_Call) Return(_a0 *url.URL, _a1 error) *MockUserManagement_GetLogoutURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_GetLogoutURL_Call) RunAndReturn(run func(usermanagement.GetLogoutURLOpts) (*url.URL, error)) *MockUserManagement_GetLogoutURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, opts
func (_m *MockUserManagement) GetUser(ctx context.Context, opts usermanagement.GetUserOpts) (usermanagement.User, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 usermanagement.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.GetUserOpts) (usermanagement.User, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.GetUserOpts) usermanagement.User); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(usermanagement.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermanagement.GetUserOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserManagement_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - opts usermanagement.GetUserOpts
func (_e *MockUserManagement_Expecter) GetUser(ctx interface{}, opts interface{}) *MockUserManagement_GetUser_Call {
	return &MockUserManagement_GetUser_Call{Call: _e.mock.On("GetUser", ctx, opts)}
}

func (_c *MockUserManagement_GetUser_Call) Run(run func(ctx context.Context, opts usermanagement.GetUserOpts)) *MockUserManagement_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermanagement.GetUserOpts))
	})
	return _c
}

func (_c *MockUserManagement_GetUser_Call) Return(_a0 usermanagement.User, _a1 error) *MockUserManagement_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_GetUser_Call) RunAndReturn(run func(context.Context, usermanagement.GetUserOpts) (usermanagement.User, error)) *MockUserManagement_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, opts
func (_m *MockUserManagement) ListUsers(ctx context.Context, opts usermanagement.ListUsersOpts) (usermanagement.ListUsersResponse, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 usermanagement.ListUsersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.ListUsersOpts) (usermanagement.ListUsersResponse, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.ListUsersOpts) usermanagement.ListUsersResponse); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(usermanagement.ListUsersResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermanagement.ListUsersOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserManagement_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - opts usermanagement.ListUsersOpts
func (_e *MockUserManagement_Expecter) ListUsers(ctx interface{}, opts interface{}) *MockUserManagement_ListUsers_Call {
	return &MockUserManagement_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, opts)}
}

func (_c *MockUserManagement_ListUsers_Call) Run(run func(ctx context.Context, opts usermanagement.ListUsersOpts)) *MockUserManagement_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermanagement.ListUsersOpts))
	})
	return _c
}

func (_c *MockUserManagement_ListUsers_Call) Return(_a0 usermanagement.ListUsersResponse, _a1 error) *MockUserManagement_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_ListUsers_Call) RunAndReturn(run func(context.Context, usermanagement.ListUsersOpts) (usermanagement.ListUsersResponse, error)) *MockUserManagement_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeInvitation provides a mock function with given fields: ctx, opts
func (_m *MockUserManagement) RevokeInvitation(ctx context.Context, opts usermanagement.RevokeInvitationOpts) (usermanagement.Invitation, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for RevokeInvitation")
	}

	var r0 usermanagement.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.RevokeInvitationOpts) (usermanagement.Invitation, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.RevokeInvitationOpts) usermanagement.Invitation); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(usermanagement.Invitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermanagement.RevokeInvitationOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_RevokeInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeInvitation'
type MockUserManagement_RevokeInvitation_Call struct {
	*mock.Call
}

// RevokeInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - opts usermanagement.RevokeInvitationOpts
func (_e *MockUserManagement_Expecter) RevokeInvitation(ctx interface{}, opts interface{}) *MockUserManagement_RevokeInvitation_Call {
	return &MockUserManagement_RevokeInvitation_Call{Call: _e.mock.On("RevokeInvitation", ctx, opts)}
}

func (_c *MockUserManagement_RevokeInvitation_Call) Run(run func(ctx context.Context, opts usermanagement.RevokeInvitationOpts)) *MockUserManagement_RevokeInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermanagement.RevokeInvitationOpts))
	})
	return _c
}

func (_c *MockUserManagement_RevokeInvitation_Call) Return(_a0 usermanagement.Invitation, _a1 error) *MockUserManagement_RevokeInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_RevokeInvitation_Call) RunAndReturn(run func(context.Context, usermanagement.RevokeInvitationOpts) (usermanagement.Invitation, error)) *MockUserManagement_RevokeInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// SendInvitation provides a mock function with given fields: ctx, opts
func (_m *MockUserManagement) SendInvitation(ctx context.Context, opts usermanagement.SendInvitationOpts) (usermanagement.Invitation, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for SendInvitation")
	}

	var r0 usermanagement.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.SendInvitationOpts) (usermanagement.Invitation, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.SendInvitationOpts) usermanagement.Invitation); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(usermanagement.Invitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermanagement.SendInvitationOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_SendInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendInvitation'
type MockUserManagement_SendInvitation_Call struct {
	*mock.Call
}

// SendInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - opts usermanagement.SendInvitationOpts
func (_e *MockUserManagement_Expecter) SendInvitation(ctx interface{}, opts interface{}) *MockUserManagement_SendInvitation_Call {
	return &MockUserManagement_SendInvitation_Call{Call: _e.mock.On("SendInvitation", ctx, opts)}
}

func (_c *MockUserManagement_SendInvitation_Call) Run(run func(ctx context.Context, opts usermanagement.SendInvitationOpts)) *MockUserManagement_SendInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermanagement.SendInvitationOpts))
	})
	return _c
}

func (_c *MockUserManagement_SendInvitation_Call) Return(_a0 usermanagement.Invitation, _a1 error) *MockUserManagement_SendInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_SendInvitation_Call) RunAndReturn(run func(context.Context, usermanagement.SendInvitationOpts) (usermanagement.Invitation, error)) *MockUserManagement_SendInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, opts
func (_m *MockUserManagement) UpdateUser(ctx context.Context, opts usermanagement.UpdateUserOpts) (usermanagement.User, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 usermanagement.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.UpdateUserOpts) (usermanagement.User, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usermanagement.UpdateUserOpts) usermanagement.User); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(usermanagement.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usermanagement.UpdateUserOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagement_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserManagement_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - opts usermanagement.UpdateUserOpts
func (_e *MockUserManagement_Expecter) UpdateUser(ctx interface{}, opts interface{}) *MockUserManagement_UpdateUser_Call {
	return &MockUserManagement_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, opts)}
}

func (_c *MockUserManagement_UpdateUser_Call) Run(run func(ctx context.Context, opts usermanagement.UpdateUserOpts)) *MockUserManagement_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usermanagement.UpdateUserOpts))
	})
	return _c
}

func (_c *MockUserManagement_UpdateUser_Call) Return(_a0 usermanagement.User, _a1 error) *MockUserManagement_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagement_UpdateUser_Call) RunAndReturn(run func(context.Context, usermanagement.UpdateUserOpts) (usermanagement.User, error)) *MockUserManagement_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserManagement creates a new instance of MockUserManagement. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserManagement(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserManagement {
	mock := &MockUserManagement{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
