name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.0"
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install tooling
        run: |
          go install -mod=readonly github.com/magefile/mage
      - name: Run all checks
        run: |
          mage -v checks
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        args: --timeout=10m