name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.22.0"
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install tooling
        run: |
          go install -mod=readonly github.com/onsi/ginkgo/v2/ginkgo
          go install -mod=readonly github.com/magefile/mage
      - name: Run all tests
        env:
          CLPOSTGRES_PORT: 5435
          CLPOSTGRES_USERNAME: postgres
          CLPOSTGRES_PASSWORD: postgres
          CLMYSQL_READ_WRITE_DATA_SOURCE_NAME: root:mysql@tcp(127.0.0.1:43306)/mysql
          CLMYSQL_READ_ONLY_DATA_SOURCE_NAME: root:mysql@tcp(127.0.0.1:43306)/mysql
          CLCEDARD_JWT_SIGNING_SECRET: "${{ secrets.CLCEDARD_JWT_SIGNING_SECRET }}"
        run: |
          mage -v test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: Test Report
          report_paths: "test-report.xml"
