name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
      - name: Check out code
        uses: actions/checkout@v3
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Install tooling
        run: |
          go install -mod=readonly github.com/onsi/ginkgo/v2/ginkgo
          go install -mod=readonly github.com/magefile/mage
      - name: Run all tests
        run: |
          mage -v test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          check_name: Test Report
          report_paths: "test-report.xml"
